# Set base image
#FROM base/manjaro:latest

#MAINTAINER Viktor Borodin

# Update pacman and install packages
#RUN pacman-db-upgrade
#RUN pacman -Syyu --noconfirm
#RUN pacman -S --noconfirm python3 pip vim ranger wget curl cronie

#RUN pip install mysql-connector-python
#RUN pip install mysql

#EXPOSE 5006
#CMD ["/bin/bash"]

